export const APP_SET_TITLE = 'APP_SET_TITLE';
export const APP_SET_CURRENT_USER = 'APP_SET_CURRENT_USER';
export const APP_OPEN_SIDEBAR = 'APP_OPEN_SIDEBAR';
export const APP_CLOSE_SIDEBAR = 'APP_CLOSE_SIDEBAR';
