export const USERS_EDITOR_FETCH_USER = 'USERS_EDITOR_FETCH_USER';
export const USERS_EDITOR_FETCH_USER_SUCCEED = 'USERS_EDITOR_FETCH_USER_SUCCEED';
export const USERS_EDITOR_FETCH_USER_FAILED = 'USERS_EDITOR_FETCH_USER_FAILED';
export const USERS_EDITOR_SAVE_USER = 'USERS_EDITOR_SAVE_USER';
export const USERS_EDITOR_SAVE_USER_SUCCEED = 'USERS_EDITOR_SAVE_USER_SUCCEED';
export const USERS_EDITOR_SAVE_USER_FAILED = 'USERS_EDITOR_SAVE_USER_FAILED';
export const USERS_EDITOR_CHANGE_FIELD = 'USERS_EDITOR_CHANGE_FIELD';
export const USERS_EDITOR_RESET = 'USERS_EDITOR_RESET';
