export const USERS_LIST_FETCH_USERS_REQUEST = 'USERS_LIST_FETCH_USERS_REQUEST';
export const USERS_LIST_FETCH_USERS_SUCCEED = 'USERS_LIST_FETCH_USERS_SUCCEED';
export const USERS_LIST_FETCH_USERS_FAILED = 'USERS_LIST_FETCH_USERS_FAILED';
export const USERS_LIST_SELECT_USER = 'USERS_LIST_SELECT_USER';
export const USERS_LIST_RESET = 'USERS_LIST_RESET';
export const USERS_LIST_NEXT_PAGE = 'USERS_LIST_NEXT_PAGE';
export const USERS_LIST_PREV_PAGE = 'USERS_LIST_PREV_PAGE';
export const USERS_LIST_CHANGE_FIELD = 'USERS_LIST_CHANGE_FIELD';
