export const USERS_LIST_FETCH_USERS = 'USERS_LIST_FETCH_USERS';
export const USERS_LIST_FETCH_USERS_SUCCEED = 'USERS_LIST_FETCH_USERS_SUCCEED';
export const USERS_LIST_FETCH_USERS_FAILED = 'USERS_LIST_FETCH_USERS_FAILED';
export const USERS_LIST_SELECT_USER = 'USERS_LIST_SELECT_USER';
export const USERS_LIST_RESET = 'USERS_LIST_RESET';
