export const FOODS_LIST_FETCH_FOODS_REQUEST = 'FOODS_LIST_FETCH_FOODS_REQUEST';
export const FOODS_LIST_FETCH_FOODS_SUCCEED = 'FOODS_LIST_FETCH_FOODS_SUCCEED';
export const FOODS_LIST_FETCH_FOODS_FAILED = 'FOODS_LIST_FETCH_FOODS_FAILED';
export const FOODS_LIST_SELECT_FOOD = 'FOODS_LIST_SELECT_FOOD';
export const FOODS_LIST_RESET = 'FOODS_LIST_RESET';
export const FOODS_LIST_NEXT_PAGE = 'FOODS_LIST_NEXT_PAGE';
export const FOODS_LIST_PREV_PAGE = 'FOODS_LIST_PREV_PAGE';
export const FOODS_LIST_CHANGE_FIELD = 'FOODS_LIST_CHANGE_FIELD';
