export const LOGIN_LOG_IN = 'LOGIN_LOG_IN';
export const LOGIN_LOG_IN_SUCCEED = 'LOGIN_LOG_IN_SUCCEED';
export const LOGIN_LOG_IN_FAILED = 'LOGIN_LOG_IN_FAILED';
export const LOGIN_CHANGE_FIELD = 'LOGIN_CHANGE_FIELD';
export const LOGIN_RESET = 'LOGIN_RESET';
