export const STATISTICS_FETCH_STATISTICS = 'STATISTICS_FETCH_STATISTICS';
export const STATISTICS_FETCH_STATISTICS_SUCCEED = 'STATISTICS_FETCH_STATISTICS_SUCCEED';
export const STATISTICS_FETCH_STATISTICS_FAILED = 'STATISTICS_FETCH_STATISTICS_FAILED';
export const STATISTICS_RESET = 'STATISTICS_RESET';
