export const MANAGE_IMPORT_FOODS = 'MANAGE_IMPORT_FOODS';
export const MANAGE_IMPORT_FOODS_SUCCEED = 'MANAGE_IMPORT_FOODS_SUCCEED';
export const MANAGE_IMPORT_FOODS_FAILED = 'MANAGE_IMPORT_FOODS_FAILED';
